name: 
run-name: ${{ github.actor }} is learning GitHub Actions
on : 
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

jobs:
  github-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: |
          npm install
          npm run build
          displayName: 'npm install & build '
      
      - name: 'Afficher l heure de début'
        run: |
          echo "Heure de début de la pipeline: $(date)"
 
      - name: 'Formater le code avec Prettier'
        run: npm run prettier
 
      - name: 'Lint du code avec ESLint'
        run: npm run lint
      
      - name: 'Vérification du coverage avec Jest'
        run: npm run coverage
      
      - name:  'Afficher l heure de fin'
        run: |
          echo "Heure de fin de la pipeline: $(date)"
      
      - name: 'Afficher le message de succès' 
        run: echo "PIPELINE SUCCESS WITHOUT ERRORS"
